version: '3'

services:
  rest-api:
    container_name: rest-api-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - DB_PASSWORD=123

  postgres:
    container_name: postgres
    image: postgres:alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=filmoteka
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=kirill

volumes:
  pgdata:
